export const SCORING = {
  GYM_POINTS: 10,
  SLEEP_POINTS: 10,
  CLEAN_EATING_POINTS: 10,
  WATER_POINTS: 10,
  MAX_STEPS_POINTS: 10,
  MAX_DAILY_POINTS: 50,
  DEFAULT_STEP_TARGET: 10000,
};

export const SESSION_DURATION_DAYS = 30;

export const DEFAULT_ADMIN_SETTINGS = {
  step_target: 10000,
  sleep_min_hours: 7.0,
  sleep_max_hours: 9.0,
  water_target_ml: 2500,
  cheat_days_enabled: true,
  day_cutoff_hour: 0,
};

export const WS_EVENTS = {
  CONNECTED: 'CONNECTED',
  CLIENT_COUNT: 'CLIENT_COUNT',
  IDENTIFY: 'IDENTIFY',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  DAILY_LOG_UPDATED: 'DAILY_LOG_UPDATED',
  WORKOUTS_ADDED: 'WORKOUTS_ADDED',
  WORKOUT_DELETED: 'WORKOUT_DELETED',
  WORKOUTS_CLEARED: 'WORKOUTS_CLEARED',
  WEIGHT_LOG_ADDED: 'WEIGHT_LOG_ADDED',
  MISSED_REASON_ADDED: 'MISSED_REASON_ADDED',
  MISSED_REASON_DELETED: 'MISSED_REASON_DELETED',
  REACTION_ADDED: 'REACTION_ADDED',
  BADGES_UPDATED: 'BADGES_UPDATED',
  SUPPLEMENT_ADDED: 'SUPPLEMENT_ADDED',
  SUPPLEMENT_DELETED: 'SUPPLEMENT_DELETED',
  SUPPLEMENT_LOG_UPDATED: 'SUPPLEMENT_LOG_UPDATED',
  CUSTOM_HABIT_ADDED: 'CUSTOM_HABIT_ADDED',
  CUSTOM_HABIT_DELETED: 'CUSTOM_HABIT_DELETED',
  CUSTOM_HABIT_LOG_UPDATED: 'CUSTOM_HABIT_LOG_UPDATED',
  GROUP_UPDATED: 'GROUP_UPDATED',
  GROUP_MEMBER_JOINED: 'GROUP_MEMBER_JOINED',
  GROUP_MEMBER_LEFT: 'GROUP_MEMBER_LEFT',
  GROUP_MEMBER_REMOVED: 'GROUP_MEMBER_REMOVED',
  INVITE_CREATED: 'INVITE_CREATED',
  INVITE_REVOKED: 'INVITE_REVOKED',
  FULL_SYNC: 'FULL_SYNC',
} as const;
